# Datasource
# If DB_HOST is not set, it defaults to localhost
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:Ashok@0042}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
# If REDIS_HOST is not set, it defaults to localhost
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379

# Server
server.port=8080

# This is the URL returned to the user.
# When using the Load Balancer, this should be port 80 (Nginx)
app.base-url=${BASE_URL:http://localhost:8080}

# Logging SQL (Add these for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Ensure transactions are committed immediately
spring.jpa.properties.hibernate.connection.autocommit=false
spring.datasource.hikari.auto-commit=true